// Generated by pm-all-in-one from custom-props.ts. Do not edit.
//
// props.ts files are checked against these shapes:
//   import type { TaskProps } from "../schema";
//   export const props = { ... } as const satisfies TaskProps;
//
// Shape only. `parentId` being a legal parent is a runtime check —
// run `pm-all-in-one doctor` for that.

interface BaseProps {
  title: string;
  /** Sole authority for the tree; null = top level under the project. */
  parentId: string | null;
  status: "draft" | "todo" | "in-progress" | "done" | "cancel";
  priority: "very-low" | "low" | "medium" | "high" | "very-high";
  startDate?: string | null;
  endDate?: string | null;
  /** Same-project issue ids that must complete before this one. */
  blockedBy?: string[];
  /** Member id who should do this; null = unassigned. */
  assignee?: string | null;
  /** System: creating member id, or null when unknown. Do not hand-edit. */
  createdBy?: string | null;
  /** System: set once at create. Do not hand-edit. */
  created: string;
  /** System: app bumps on props or body write. Do not hand-edit. */
  updated: string;
  /** Ids live in directory names only. */
  id?: never;
}

export interface EpicProps extends BaseProps {
  level: "epic";
}

export interface TaskProps extends BaseProps {
  level: "task";
  /** Note */
  movementField1?: string;
}

export interface SubtaskProps extends BaseProps {
  level: "subtask";
}

export type IssueProps = EpicProps | TaskProps | SubtaskProps;
