import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/** Identifies a shim as ours, so callers may safely replace it. */
export const SHIM_MARKER = "# Generated by pm-all-in-one — do not edit";

export type LocalPmShim = {
  binDir: string;
  shimPath: string;
};

/**
 * Install `pm-all-in-one` shim under userData/bin so the in-app terminal PATH can find it.
 * Uses ELECTRON_RUN_AS_NODE so the Electron binary runs cli.js as Node.
 *
 * ↔ electron/core/desktop/cli-install.ts — links this shim into a PATH directory
 */
export function ensureLocalPmShim(userDataDir: string): LocalPmShim {
  const binDir = path.join(userDataDir, "bin");
  fs.mkdirSync(binDir, { recursive: true });
  const shimPath = path.join(binDir, "pm-all-in-one");
  const electronPath = process.execPath;
  const cliPath = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    "..",
    "..",
    "cli.js",
  );
  const body = `#!/bin/sh
${SHIM_MARKER}
ELECTRON_RUN_AS_NODE=1 exec "${electronPath}" "${cliPath}" "$@"
`;
  let existing = "";
  try {
    existing = fs.readFileSync(shimPath, "utf8");
  } catch {
    // create
  }
  if (existing !== body) {
    fs.writeFileSync(shimPath, body, { mode: 0o755 });
  } else {
    try {
      fs.chmodSync(shimPath, 0o755);
    } catch {
      // ignore
    }
  }
  return { binDir, shimPath };
}
