// Generated by pm-all-in-one from wiki/custom-props.ts. Do not edit.
//
// wiki-node props.ts files are checked against this shape:
//   import type { WikiNodeProps } from "../schema";
//   export const props = { ... } as const satisfies WikiNodeProps;
//
// Markdown custom fields live in sibling .md files, never in props.ts.
// wiki-node fields are string[] of wiki-node ids (existence is doctor).
// string-list fields are string[] of free-text tokens, not wiki ids.

export interface WikiNodeProps {
  title: string;
  /** Short blurb; required key, may be "". */
  description: string;
  status: "todo" | "in-progress" | "done";
  /** System: creating member id, or null when unknown. Do not hand-edit. */
  createdBy?: string | null;
  /** System: set once at create. Do not hand-edit. */
  created: string;
  /** System: app bumps on props or body write. Do not hand-edit. */
  updated: string;
  /** Ids live in directory names only. */
  id?: never;
}

