/**
 * Generate `<project>/schema.d.ts` so an agent editing props.ts by hand gets
 * told about a misspelled field before the app ever loads the file.
 *
 * Types constrain shape, not relationships: `parentId: "w_7"` is just a string to
 * the type system, and nothing here can tell whether w7 is a legal parent. That
 * check has to stay at runtime in `ladder.ts`.
 *
 * Flat storage keeps the import specifier constant — a props.ts is always
 * exactly one directory below its project.
 */
import fs from "node:fs";
import path from "node:path";

import type { CustomPropDef, CustomPropsSchema, IssueLevel } from "./types.js";
import { ISSUE_PRIORITY_IDS } from "./issue-priority.js";
import { ISSUE_STATUS_IDS } from "./issue-status.js";

const TS_TYPE: Record<CustomPropDef["type"], string> = {
  string: "string",
  number: "number",
  boolean: "boolean",
  date: "string",
  markdown: "never",
};

export const LEVEL_TYPE_NAME: Record<IssueLevel, string> = {
  epic: "EpicProps",
  task: "TaskProps",
  subtask: "SubtaskProps",
};

function isSafeIdentifier(key: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
}

function renderLevel(level: IssueLevel, defs: readonly CustomPropDef[]): string {
  const lines = [`export interface ${LEVEL_TYPE_NAME[level]} extends BaseProps {`];
  lines.push(`  level: ${JSON.stringify(level)};`);
  for (const def of defs) {
    // Markdown props live in sibling .md files, never in props.ts.
    if (def.type === "markdown") {
      continue;
    }
    const key = isSafeIdentifier(def.key) ? def.key : JSON.stringify(def.key);
    const doc = def.help?.trim()
      ? `${def.label} — ${def.help.trim()}`
      : def.label;
    lines.push(`  /** ${doc.replace(/\*\//g, "* /")} */`);
    lines.push(`  ${key}?: ${TS_TYPE[def.type]};`);
  }
  lines.push("}");
  return lines.join("\n");
}

export function renderSchemaDts(schema: CustomPropsSchema): string {
  return `${[
    "// Generated by pm-all-in-one from custom-props.ts. Do not edit.",
    "//",
    "// props.ts files are checked against these shapes:",
    '//   import type { TaskProps } from "../schema";',
    "//   export const props = { ... } as const satisfies TaskProps;",
    "//",
    "// Shape only. `parentId` being a legal parent is a runtime check —",
    "// run `pm-all-in-one doctor` for that.",
    "",
    "interface BaseProps {",
    "  title: string;",
    '  /** Sole authority for the tree; null = top level under the project. */',
    "  parentId: string | null;",
    `  status: ${ISSUE_STATUS_IDS.map((id) => JSON.stringify(id)).join(" | ")};`,
    `  priority: ${ISSUE_PRIORITY_IDS.map((id) => JSON.stringify(id)).join(" | ")};`,
    "  startDate?: string | null;",
    "  endDate?: string | null;",
    "  estimatePoint?: number;",
    "  /** Same-project issue ids that must complete before this one. */",
    "  blockedBy?: string[];",
    "  /** Member id who should do this; null = unassigned. */",
    "  assignee?: string | null;",
    "  /** System: creating member id, or null when unknown. Do not hand-edit. */",
    "  createdBy?: string | null;",
    "  /** System: set once at create. Do not hand-edit. */",
    "  created: string;",
    "  /** System: app bumps on props or body write. Do not hand-edit. */",
    "  updated: string;",
    "  /** Ids live in directory names only. */",
    "  id?: never;",
    "}",
    "",
    renderLevel("epic", schema.epic),
    "",
    renderLevel("task", schema.task),
    "",
    renderLevel("subtask", schema.subtask),
    "",
    "export type IssueProps = EpicProps | TaskProps | SubtaskProps;",
  ].join("\n")}\n`;
}

export function schemaDtsPath(projectDir: string): string {
  return path.join(projectDir, "schema.d.ts");
}

/**
 * No-op when the rendered output already matches on disk. `schema.d.ts` lives
 * inside the watched `issue-hierarchy/` tree, so an unconditional write makes
 * `rebuildIndex` retrigger the watcher that called it — a change-event loop that
 * keeps the whole UI refetching a couple of times per second.
 */
export function writeSchemaDts(
  projectDir: string,
  schema: CustomPropsSchema,
): void {
  const file = schemaDtsPath(projectDir);
  const next = renderSchemaDts(schema);
  if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === next) {
    return;
  }
  fs.writeFileSync(file, next, "utf8");
}
